# Project-wide Gradle settings.

# Memory and Parallel Builds
org.gradle.jvmargs=-Xmx4096m -XX:+UseParallelGC -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true
org.gradle.workers.max=4
org.gradle.configureondemand=true
org.gradle.caching=true
org.gradle.incremental=true

# AndroidX
android.useAndroidX=true
android.enableJetifier=false

# Features
newArchEnabled=true
hermesEnabled=true
edgeToEdgeEnabled=false

# Parallel APK build
android.enableParallelApkBuild=true
reactNativeArchitectures=arm64-v8a
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8

