import { StyleSheet } from 'react-native';

export const st = StyleSheet.create({
  screen: {
    flex: 1,
    overflow: 'hidden',
  },
  center: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  lightningFlash: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#FFFFFF',
  },
  scrollContent: {
    paddingHorizontal: 20,
  },
  loadingText: {
    color: '#E2E8F0',
    marginTop: 16,
    fontSize: 16,
    fontWeight: '700',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  appTitle: {
    color: '#64748B',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 3,
    textTransform: 'uppercase',
  },
  locationText: {
    color: '#F1F5F9',
    fontSize: 23,
    fontWeight: '900',
    marginTop: 2,
  },
  refreshBtn: {
    width: 52,
    height: 52,
    borderRadius: 26,
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
  },
  refreshIcon: {
    fontSize: 26,
    fontWeight: '900',
  },
  noticeBox: {
    backgroundColor: 'rgba(30, 41, 59, 0.38)',
    borderWidth: 1,
    borderColor: 'rgba(71, 85, 105, 0.45)',
    borderRadius: 18,
    padding: 14,
    marginBottom: 16,
  },
  noticeText: {
    color: '#CBD5E1',
    fontSize: 13,
    fontWeight: '600',
  },
  cachedText: {
    color: '#94A3B8',
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 12,
    textAlign: 'center',
  },
  heroCard: {
    borderRadius: 38,
    padding: 14,
    backgroundColor: 'rgba(30, 41, 59, 0.72)',
    borderWidth: 1.5,
    borderColor: 'rgba(148, 163, 184, 0.28)',
    alignItems: 'center',
    marginBottom: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 25 },
    shadowOpacity: 0.45,
    shadowRadius: 45,
    elevation: 12,
  },
  tempText: {
    color: '#F8FAFC',
    fontSize: 76,
    lineHeight: 82,
    fontWeight: '900',
    marginTop: -4,
    letterSpacing: -2,
  },
  conditionText: {
    fontSize: 22,
    fontWeight: '900',
    letterSpacing: -0.5,
  },
  updatedText: {
    color: '#94A3B8',
    fontSize: 13,
    fontWeight: '600',
    marginTop: 6,
    marginBottom: 20,
  },
  rainCard: {
    width: '100%',
    borderRadius: 24,
    borderWidth: 1.5,
    paddingVertical: 14,
    paddingHorizontal: 14,
    marginTop: 8,
  },
  rainCardRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  rainTimerBlock: {
    flex: 1,
    alignItems: 'center',
  },
  rainTimerDivider: {
    width: 1,
    height: 58,
    backgroundColor: 'rgba(148, 163, 184, 0.25)',
    marginHorizontal: 10,
  },
  rainTimerIcon: {
    fontSize: 24,
    marginBottom: 5,
  },
  rainTimerLabel: {
    color: '#94A3B8',
    fontSize: 11,
    fontWeight: '800',
    marginBottom: 4,
    textAlign: 'center',
  },
  rainTimerClock: {
    color: '#F1F5F9',
    fontSize: 17,
    fontWeight: '900',
    textAlign: 'center',
  },
  rainTimerClockSmall: {
    fontSize: 13,
    lineHeight: 17,
  },
  rainChanceLabel: {
    color: '#94A3B8',
    textAlign: 'center',
    fontSize: 12.5,
    fontWeight: '700',
    marginTop: 10,
  },
  metricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  metricCard: {
    width: '48%',
    borderRadius: 26,
    padding: 18,
    backgroundColor: 'rgba(30, 41, 59, 0.58)',
    borderWidth: 1.5,
    borderColor: 'rgba(148, 163, 184, 0.22)',
    marginBottom: 12,
  },
  metricLabel: {
    color: '#94A3B8',
    fontSize: 13,
    fontWeight: '700',
  },
  metricValue: {
    fontSize: 29,
    fontWeight: '900',
    marginTop: 8,
  },
  metricSub: {
    color: '#64748B',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 4,
  },
  todayCard: {
    borderRadius: 32,
    padding: 22,
    backgroundColor: 'rgba(30, 41, 59, 0.58)',
    borderWidth: 1.5,
    borderColor: 'rgba(148, 163, 184, 0.22)',
    marginBottom: 22,
  },
  todayRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 18,
  },
  todayBadge: {
    fontSize: 19,
    fontWeight: '900',
  },
  sunRow: {
    flexDirection: 'row',
  },
  sunBox: {
    flex: 1,
    borderRadius: 22,
    padding: 18,
    backgroundColor: 'rgba(15, 23, 42, 0.78)',
    marginRight: 10,
  },
  sunBoxLast: {
    flex: 1,
    borderRadius: 22,
    padding: 18,
    backgroundColor: 'rgba(15, 23, 42, 0.78)',
  },
  sunIcon: {
    fontSize: 26,
  },
  sunLabel: {
    color: '#94A3B8',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 8,
  },
  sunValue: {
    color: '#F1F5F9',
    fontSize: 16,
    fontWeight: '900',
    marginTop: 4,
  },
  sectionHeader: {
    marginTop: 8,
    marginBottom: 14,
  },
  sectionTitle: {
    color: '#F1F5F9',
    fontSize: 19.5,
    fontWeight: '900',
  },
  sectionSub: {
    color: '#94A3B8',
    fontSize: 13,
    fontWeight: '600',
    marginTop: 3,
  },
  hourlyList: {
    paddingRight: 20,
    paddingBottom: 20,
  },
  hourCard: {
    width: 82,
    paddingVertical: 16,
    borderRadius: 26,
    borderWidth: 1.5,
    alignItems: 'center',
    marginRight: 12,
  },
  hourLabel: {
    color: '#94A3B8',
    fontSize: 12,
    fontWeight: '700',
  },
  hourIcon: {
    fontSize: 29,
    marginTop: 10,
    marginBottom: 4,
  },
  hourTemp: {
    color: '#F1F5F9',
    fontSize: 18,
    fontWeight: '900',
    marginTop: 4,
  },
  hourRain: {
    color: '#94A3B8',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 6,
  },
  hourMm: {
    color: '#67E8F9',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 2,
  },
  infoCard: {
    borderRadius: 28,
    padding: 20,
    backgroundColor: 'rgba(30, 41, 59, 0.58)',
    borderWidth: 1.5,
    borderColor: 'rgba(148, 163, 184, 0.22)',
    marginBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  infoTitle: {
    color: '#94A3B8',
    fontSize: 13,
    fontWeight: '700',
  },
  infoLabel: {
    fontSize: 21,
    fontWeight: '900',
    marginTop: 6,
  },
  infoMessage: {
    color: '#94A3B8',
    fontSize: 12.5,
    fontWeight: '600',
    marginTop: 6,
    lineHeight: 18,
  },
  infoValue: {
    fontSize: 36,
    fontWeight: '900',
    alignSelf: 'center',
    marginLeft: 16,
  },
  footer: {
    textAlign: 'center',
    color: '#64748B',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    marginTop: 12,
    opacity: 0.75,
  },
  errorIcon: {
    fontSize: 48,
    marginBottom: 16,
  },
  errorTitle: {
    color: '#F1F5F9',
    fontSize: 23,
    fontWeight: '900',
    marginBottom: 10,
    textAlign: 'center',
  },
  errorText: {
    color: '#94A3B8',
    fontSize: 15,
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: 23,
    marginBottom: 24,
  },
  primaryBtn: {
    paddingHorizontal: 26,
    paddingVertical: 15,
    borderRadius: 20,
    marginBottom: 12,
  },
  primaryBtnText: {
    color: '#0F172A',
    fontSize: 15,
    fontWeight: '900',
  },
  secondaryBtn: {
    paddingHorizontal: 26,
    paddingVertical: 15,
    borderRadius: 20,
    backgroundColor: 'rgba(30, 41, 59, 0.55)',
    borderWidth: 1.5,
    borderColor: 'rgba(148, 163, 184, 0.3)',
  },
  secondaryBtnText: {
    color: '#F1F5F9',
    fontSize: 15,
    fontWeight: '900',
  },
});
